### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by prographo** [input-output-hk/mallet#13]
Without making any changes at all, breaks:

```
git clone https://github.com/input-output-hk/mallet.git
cd mallet
npm install
./mallet --help
/home/ubuntu/MALLET/mallet/lib/mallet.js:51
  const dim = function(n, l = 1n, r = 0n) {
                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/MALLET/mallet/cli.js:3:16)
```

**Comment by prographo** [comment]
I had to remove node, link node to point to nodejs, clean npm module cache

then:

npm install -g --engine-strict @iohk/mallet

worked
