### ISSUE TITLE
./mallet --version

### ISSUE THREAD

**Issue by trismegistus-root** [input-output-hk/mallet#28]
Typing -

`./mallet --version`

Gives -

```
internal/modules/cjs/loader.js:638
    throw err;
Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mallet/lib/web3/web3/jsonrpc.js:25:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I am just trying to check my version, so this is disconcerting. I can see that I have all the necessaries listed here: https://developers.cardano.org/en/virtual-machines/kevm/getting-started/mallet-end-to-end/

But this simple command is throwing an error.

**Comment by xlcrr** [comment]
Works for me on fresh install `v2.1.0`
