### ISSUE TITLE
Iele faucet returns vague error

### ISSUE THREAD

**Issue by hoffw** [input-output-hk/mallet#29]
Thrown: 'Faucet error: undefined' upon `requestFunds()` from Mallet with Iele set up as the network used. 

![image](https://user-images.githubusercontent.com/76015073/106944876-bf232a80-66ec-11eb-971e-d02af9713be6.png)

**Comment by jspdown** [comment]
I'm experiencing the same problem as @Whoffie. It also happens on the `getBalance()` command:
```
mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/home/jspdown/Sides/mallet/lib/web3/web3/errors.js:38:16)
    at HttpProvider.send (/home/jspdown/Sides/mallet/lib/web3/web3/httpprovider.js:102:18)
    at RequestManager.send (/home/jspdown/Sides/mallet/lib/web3/web3/requestmanager.js:65:32)
    at Eth.send [as getBalance] (/home/jspdown/Sides/mallet/lib/web3/web3/method.js:145:58)
    at Mallet.getBalance (/home/jspdown/Sides/mallet/lib/mallet.js:238:26)
```

Tested on Mallet 2.1.0 and Node v10.16.3 as specified in the documentation. 
Mallet started using `./mallet iele -d ./data`.

**Comment by jspdown** [comment]
I digged a but deeper in the problem and added some logs in the web3 HTTPprovider. When making an HTTP call I get the following properties in the request object:
```js
{ jsonrpc: '2.0',
  id: 'mallet_df1a7b1d-3d7e-4c69-b5cc-9dd77e8d1611',
  method: 'eth_getBalance',
  params: [ '0x89feaa82b11a1b96a9f582111111111111111111', 'latest' ] } { UNSENT: 0,
  readyState: 4,
  onreadystatechange: null,
  responseText: undefined,
  responseXML: '',
  status: 0,
  statusText: { code: 'CERT_HAS_EXPIRED' },
  withCredentials: true,
...}
```

There seems to be an issue with the certificate (`CERT_HAS_EXPIRED`):
```
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = *.iele.mantis.iohkdev.io
verify error:num=10:certificate has expired
notAfter=Jul 25 12:00:00 2020 GMT
verify return:1
depth=0 CN = *.iele.mantis.iohkdev.io
notAfter=Jul 25 12:00:00 2020 GMT
verify return:1
```

As a workaround until this get fixed, you can start mallet this way:

 ```
 NODE_TLS_REJECT_UNAUTHORIZED=0 ./mallet iele -d ./data
 ```
 
 Can someone renew the certificate?
 
 Then, on `requestFunds`, I get the following error:
 ```
 Thrown: 'Faucet error: Request is missing required query parameter \'address\''
 ```
 
 Apparently, the faucet was modified in https://github.com/input-output-hk/mallet/pull/24/files but the deployed faucet still want the `address` query parameter.

**Comment by rxdn** [comment]
Cert on rpc-kevm.portal.dev.cardano.org has expired again, 4 days ago

**Comment by johnnynuuma** [comment]
Indeed SSL Cert expired -- following worked for me:

`mallet> a = newAccount('yada')
'0x62653a23aa1c62779dea5ea045b9027a093cb8dd'

mallet> selectAccount(a)
'0x62653a23aa1c62779dea5ea045b9027a093cb8dd'

mallet> currentAccount()
'0x62653a23aa1c62779dea5ea045b9027a093cb8dd'

mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/home/jhl/.nvm/versions/node/v10.16.3/lib/node_modules/@iohk/mallet/lib/web3/web3/errors.js:38:16)
    at HttpProvider.send (/home/jhl/.nvm/versions/node/v10.16.3/lib/node_modules/@iohk/mallet/lib/web3/web3/httpprovider.js:102:18)
    at RequestManager.send (/home/jhl/.nvm/versions/node/v10.16.3/lib/node_modules/@iohk/mallet/lib/web3/web3/requestmanager.js:65:32)
    at Eth.send [as getBalance] (/home/jhl/.nvm/versions/node/v10.16.3/lib/node_modules/@iohk/mallet/lib/web3/web3/method.js:145:58)
    at Mallet.getBalance (/home/jhl/.nvm/versions/node/v10.16.3/lib/node_modules/@iohk/mallet/lib/mallet.js:232:26)

--ouch!!!!
--try this:
mallet> process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
--check account again
mallet> currentAccount()
'0x62653a23aa1c62779dea5ea045b9027a093cb8dd'
mallet> getBalance()
'0'
--sweet!!
--requestFunds should work, but .....
mallet> requestFunds()
'0x1636a566e7bdc1cc48b78e24ebcc5733fc495904799ec4aca95ed597a8a70969'
mallet> getBalance()
'0'
--ouch! wtf????
--ok, try this
mallet> requestFunds(a)
Thrown: 'Faucet error: The user has sent too many requests in a given amount of time.'
mallet> requestFunds(a)
'0xe956006947e9c0ce26f0e481438a9fab5af5dbf68b1a1f14ef318430d9e34a37'
mallet> getBalance()
'60000000000000000'
--sweet

Gotta say yuck!  
Below are the SSL Certificate Details -- this is not nice been expired almost 1 year.  
Please update SSL Cert or at minimum update ReadMe to clearly indicate what works and doesn't.

![Screenshot from 2021-05-19 15-48-39](https://user-images.githubusercontent.com/22530182/118894940-0a3b0500-b8ba-11eb-9e65-e97b87cad6d3.png)

**Comment by feedbackloops** [comment]
Any progress on this? Seems to be a problem affecting many users.
Personally, I can connect to the testnet with `NODE_TLS_REJECT_UNAUTHORIZED=0`.
But I'm getting an error when I attempt to requestFunds, in trying both `requestFunds()` and `requestFunds(newAccountAddr)`
`Thrown: 'Faucet error: Request is missing required query parameter \'address\''`

**Comment by pkellyiohk** [comment]
Hi all,

Apologies for the difficulties you are experiencing.
However, at the moment we are working on releasing a new and improved IELE VM and the existing IELE Devnet is not currently operational. 
Please check https://developers.cardano.org/en/virtual-machines/iele/overview/ for info and updatesand note the 
"Please note that at this point in time we are restarting and accelerating the K Ethereum Virtual Machine (KEVM) program only. The IELE program will be coming very soon."

Thank you for your ongoing interest and support of IOHK and in particular, the IELE VM implementation.

PK.

**Comment by xlcrr** [comment]
In `lib/mallet.js` simply change the faucetUrl to accept the `?address=` query string 


```
  requestFunds(addr)  {
    const address = this.resolveAddress(addr);
    // const queryUrl = this.faucetUrl;
    const queryUrl = this.faucetUrl + '?address=' + address;
```

`requestFunds()` now works
