### ISSUE TITLE
getBalance()

### ISSUE THREAD

**Issue by ghost** [input-output-hk/mallet#34]
i followed the guide but at getBalance() I get this error.

mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/mnt/c/pr0/mallet/lib/web3/web3/errors.js:38:16)
    at HttpProvider.send (/mnt/c/pr0/mallet/lib/web3/web3/httpprovider.js:102:18)
    at RequestManager.send (/mnt/c/pr0/mallet/lib/web3/web3/requestmanager.js:65:32)
    at Eth.send [as getBalance] (/mnt/c/pr0/mallet/lib/web3/web3/method.js:145:58)
    at Mallet.getBalance (/mnt/c/pr0/mallet/lib/mallet.js:238:26)

**Comment by adityak74** [comment]
I am also getting the same error as well. 

mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: "Bad Gateway"
    at Object.InvalidResponse (/home/cardano/mallet/lib/web3/web3/errors.js:38:16)
    at HttpProvider.send (/home/cardano/mallet/lib/web3/web3/httpprovider.js:102:18)
    at RequestManager.send (/home/cardano/mallet/lib/web3/web3/requestmanager.js:65:32)
    at Eth.send [as getBalance] (/home/cardano/mallet/lib/web3/web3/method.js:145:58)
    at Mallet.getBalance (/home/cardano/mallet/lib/mallet.js:238:26)

**Comment by ghost** [comment]
Its broken, you should learn Plutus if you want to write safe smart contracts or wait for the erc-20 converter


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xlcrr** [comment]
any update? Same error

Do we need to run another command in another terminal window for this to communicate with testnet or something and get access to `this.provider.send` on the `requestmanager.js`? eg: 

https://ethereum.stackexchange.com/questions/23719/invalid-json-rpc-response-undefined-when-running-web3-eth-accounts-node
